pages.lots=['วางแผนล็อตและวันรับของ','ทดลองอายุสินค้าและเวลารอรับ ร่วมกับยอดขายที่คาดการณ์'];
const lotNav=document.createElement('button');lotNav.dataset.page='lots';lotNav.textContent='วันหมดอายุ / เวลารับของ';lotNav.addEventListener('click',()=>showPage('lots'));document.querySelector('.nav').append(lotNav);
const lotView=document.createElement('div');lotView.className='view';lotView.dataset.view='lots';lotView.hidden=true;
lotView.innerHTML=`<section class="card"><h2>วางแผนซื้อโดยดูแต่ละล็อต</h2><div class="info-strip">เงื่อนไขทดลองที่คุณกรอก ไม่ใช่วันหมดอายุหรือเวลาขนส่งจริงจาก M5 · วันที่เริ่มวางแผน 23 พ.ค. 2016</div><p class="note">กรอกของที่มีอยู่ตอนเริ่มวัน ใช้ล็อตที่หมดอายุก่อนก่อน สินค้าใช้ขายได้ถึงสิ้นวันหมดอายุ ข้อมูลในหน้านี้ยังไม่บันทึกถาวร</p><div class="inputs"><div><label for="lot-item">สินค้า</label><select id="lot-item"></select></div><div><label for="lot-lead">เวลารอรับหลังสั่ง (วัน)</label><input id="lot-lead" type="number" min="0" max="30" step="1" value="2"></div><div><label for="lot-shelf">อายุขายของใหม่ รวมวันรับ (วัน)</label><input id="lot-shelf" type="number" min="1" max="30" step="1" value="3"></div><div><label for="lot-pack">หน่วยต่อแพ็ก</label><input id="lot-pack" type="number" min="1" max="1000000" step="1" value="1"></div></div><h3>สต็อกปัจจุบันแยกล็อต</h3><div id="lot-inputs"></div><button id="lot-add" class="secondary">เพิ่มล็อต</button><button id="lot-run">คำนวณแผนซื้อ</button><p id="lot-error" class="error" role="alert"></p></section><section id="lot-output" class="card" hidden aria-live="polite"><h2 id="lot-summary"></h2><p id="lot-dates"></p><div class="info-strip" id="lot-warning"></div><p id="lot-extra" class="note"></p><div class="saved-table-wrap"><table class="saved-table"><thead><tr><th>วันที่</th><th>คาดขาย</th><th>ใช้ของเดิม</th><th>ส่วนที่ของเดิมไม่พอ</th><th>ของเดิมที่หมดอายุก่อนขาย</th></tr></thead><tbody id="lot-days"></tbody></table></div><button id="lot-export" class="secondary">ดาวน์โหลดแผน CSV</button></section><section class="card"><h2>วิธีคำนวณและข้อจำกัด</h2><p class="note">เริ่มจากโมเดล Linear Regression เดิม แล้วใช้คำทำนายแต่ละวันต่อเป็นข้อมูลวันถัดไป โดยไม่ใช้ยอดขายจริงในอนาคต การทำนายหลายวันนี้ยังไม่ได้รับการประเมินแบบเดียวกับคะแนนทำนายหนึ่งวัน</p><p class="note">จำลองการใช้ของเดิมตามยอดคาดการณ์ จากนั้นรวมส่วนที่ไม่พอในช่วงวันรับถึงวันหมดอายุของล็อตใหม่ และปัดขึ้นตามแพ็ก สั่งวันนี้ รับตอนเริ่มวันรับของ สมมุติยังไม่มีสินค้าอื่นกำลังส่ง และวางแผนซื้อครั้งเดียวครอบคลุมอายุล็อตใหม่</p><p class="note">ส่วนต่างและของหมดอายุในตารางเป็นค่าคาดการณ์ จึงมีทศนิยมได้ จำนวนซื้อจริงเป็นจำนวนเต็ม ไม่ใช่ผลพิสูจน์ว่าลดของเสียได้ ระยะทางยังไม่ใช้คำนวณ: ให้กรอกเวลารอรับที่คาดไว้โดยตรง</p></section>`;
document.querySelector('.footnote').before(lotView);
for(const code of Object.keys(builtInModels)){const option=document.createElement('option');option.value=code;option.textContent=code;byId('lot-item').append(option)}
let lotResult=null,lotSequence=0;
function clearLotResult(){lotResult=null;byId('lot-output').hidden=true;byId('lot-error').textContent=''}
function addLot(qty='',expiry=''){
 if(byId('lot-inputs').children.length>=50){byId('lot-error').textContent='รองรับไม่เกิน 50 ล็อต';return}
 const id=++lotSequence,row=document.createElement('div');row.className='inputs lot-input-row';
 row.innerHTML=`<div><label for="lot-qty-${id}">จำนวนล็อต ${id} (หน่วย)</label><input id="lot-qty-${id}" class="lot-qty" type="number" min="0" max="1000000" step="1"></div><div><label for="lot-expiry-${id}">วันหมดอายุล็อต ${id}</label><input id="lot-expiry-${id}" class="lot-expiry" type="date"></div><div><button type="button" class="secondary">ลบล็อต ${id}</button></div>`;
 row.querySelector('.lot-qty').value=qty;row.querySelector('.lot-expiry').value=expiry;
 row.querySelector('button').addEventListener('click',()=>{row.remove();clearLotResult()});row.addEventListener('input',clearLotResult);byId('lot-inputs').append(row);clearLotResult();
}
byId('lot-add').addEventListener('click',()=>addLot());
['item','lead','shelf','pack'].forEach(k=>byId('lot-'+k).addEventListener(k==='item'?'change':'input',clearLotResult));
byId('lot-run').addEventListener('click',()=>{clearLotResult();try{
 const options=Object.fromEntries(['lead','shelf','pack'].map(k=>{const value=byId('lot-'+k).value;if(!value.trim())throw new Error('กรอกเงื่อนไขให้ครบ');return [k,Number(value)]}));
 const lots=Array.from(byId('lot-inputs').children).map(row=>{const q=row.querySelector('.lot-qty').value,e=row.querySelector('.lot-expiry').value;if(!q.trim()||!e)throw new Error('กรอกจำนวนและวันหมดอายุทุกล็อต หรือลบล็อตที่ไม่ใช้');return {qty:Number(q),expires:e}});
 const item=byId('lot-item').value,r=planLots(builtInModels[item],options,lots,infer);lotResult={item,options,lots,...r};
 byId('lot-summary').textContent=`แนะนำซื้อ ${r.units} หน่วย (${r.packs} แพ็ก)`;
 byId('lot-dates').textContent=`${item} · สั่ง ${r.start} · รับ ${r.arrival} · ขายล็อตใหม่ได้ถึง ${r.expiry}`;
 byId('lot-warning').textContent=r.waitShortage>0?`ระหว่างรอรับ ของเดิมอาจไม่พอประมาณ ${r.waitShortage.toFixed(2)} หน่วย การสั่งครั้งนี้มาถึงไม่ทันแก้ส่วนนี้`:'ของเดิมคาดว่าเพียงพอระหว่างรอรับสินค้า';
 byId('lot-extra').textContent=`ต้องเติมช่วงอายุล็อตใหม่ประมาณ ${r.need.toFixed(2)} หน่วย · ส่วนเกินจากการปัดแพ็ก ${r.packExcess.toFixed(2)} หน่วยอาจขายไม่ทัน · ของเดิมที่หมดอายุก่อนขายในช่วงแผนประมาณ ${r.expired.toFixed(2)} หน่วย`;
 byId('lot-days').replaceChildren();for(const d of r.rows){const tr=document.createElement('tr');for(const v of [d.date,...['demand','existingUsed','missing','expired'].map(k=>d[k].toFixed(2))]){const td=document.createElement('td');td.textContent=v;tr.append(td)}byId('lot-days').append(tr)}byId('lot-output').hidden=false;
 }catch(e){byId('lot-error').textContent=e.message}});
byId('lot-export').addEventListener('click',()=>{if(!lotResult)return;const r=lotResult;downloadCSV([['สินค้า','วันสั่ง','วันรับ','วันหมดอายุล็อตใหม่','หน่วยต่อแพ็ก','จำนวนซื้อ','วันที่','คาดขาย','ใช้ของเดิม','ส่วนที่ของเดิมไม่พอ','หมดอายุก่อนขาย'],...r.rows.map(d=>[r.item,r.start,r.arrival,r.expiry,r.options.pack,r.units,d.date,d.demand,d.existingUsed,d.missing,d.expired])],'lot_plan.csv')});
