pages.simulation=['ทดลองจำลองการซื้อ','ย้อนเวลาใช้ยอดขายจริง M5 แล้วลองเปลี่ยนเงื่อนไข'];
const simNav=document.createElement('button');simNav.dataset.page='simulation';simNav.textContent='ทดลองอายุสินค้า / ขนส่ง';simNav.addEventListener('click',()=>showPage('simulation'));document.querySelector('.nav').append(simNav);
const simView=document.createElement('div');simView.className='view';simView.dataset.view='simulation';simView.hidden=true;
simView.innerHTML=`<section class="card"><h2>ลองเป็นเจ้าของร้านย้อนหลัง 28 วัน</h2><div class="info-strip">ยอดขายเป็นข้อมูลจริง M5 · อายุสินค้าและเวลาส่งเป็นเงื่อนไขสมมุติ ไม่ใช่ข้อมูลจริงของสินค้าเหล่านี้</div><p class="note">1. เลือกสินค้าและเงื่อนไข → 2. สั่งซื้อโดยเห็นเฉพาะยอดขายที่ผ่านมา → 3. รับของและขายตามยอดจริง → 4. ดูของขาดและของหมดอายุ</p><div class="inputs"><div><label for="sim-item">สินค้าที่ทดลอง</label><select id="sim-item"></select></div><div><label for="sim-lead">รอรับสินค้าหลังสั่ง (วัน)</label><input id="sim-lead" type="number" min="1" max="30" value="1"></div><div><label for="sim-shelf">อายุขายหลังรับเข้า (วัน รวมวันรับ)</label><input id="sim-shelf" type="number" min="1" max="30" value="2"></div><div><label for="sim-review">สั่งซื้อทุกกี่วัน</label><input id="sim-review" type="number" min="1" max="30" value="1"></div><div><label for="sim-pack">จำนวนหน่วยต่อแพ็ก</label><input id="sim-pack" type="number" min="1" max="30" value="1"></div><div><label for="sim-initial">ของเริ่มต้น (หน่วย)</label><input id="sim-initial" type="number" min="0" max="100000" value="10"></div></div><button id="sim-run">เริ่มจำลอง 28 วัน</button><p id="sim-error" class="error" role="alert"></p></section><section id="sim-output" class="card" hidden aria-live="polite"><h2>ผลเปรียบเทียบภายใต้เงื่อนไขเดียวกัน</h2><p id="sim-description" class="note"></p><div class="saved-table-wrap"><table class="saved-table"><thead><tr><th>วิธีสั่งซื้อ</th><th>ของขาด</th><th>หมดอายุ</th><th>รองรับยอดขาย</th><th>เหลือ / กำลังส่ง</th></tr></thead><tbody id="sim-summary"></tbody></table></div><p id="sim-verdict"></p><button id="sim-export" class="secondary">ดาวน์โหลดรายละเอียดทั้งสองวิธี CSV</button><details open><summary>ดูเหตุการณ์รายวันของ AI</summary><div class="saved-table-wrap"><table class="saved-table"><thead><tr><th>วันที่</th><th>สั่งซื้อ</th><th>รับของ</th><th>ยอดจริง</th><th>ขายได้</th><th>ขาด</th><th>หมดอายุ</th><th>เหลือ</th></tr></thead><tbody id="sim-days"></tbody></table></div></details></section><section class="card"><h2>อ่านผลอย่างไร?</h2><p class="note">ของขาด = จำนวนที่สต็อกรองรับยอดขาย M5 ไม่ได้ · หมดอายุ = ของเหลือเมื่อจบวันหมดอายุ · รองรับยอดขาย = ขายได้ในการจำลอง ÷ ยอดขาย M5 ไม่ใช่ accuracy ของโมเดล</p><p class="note">สั่งตอนเริ่มวัน ก่อนรู้ยอดขายวันนั้น รับของก่อนขาย ใช้ล็อตหมดอายุก่อนขายก่อน (FEFO) ไม่มีสต็อกเผื่อหรือจำกัดงบ เริ่มต้นไม่มีของกำลังส่ง ของเริ่มต้นมีอายุเท่าค่าที่กรอก จึงอาจขาดช่วงรอรับล็อตแรก</p><p class="note">AI ใช้ Linear Regression ที่ฝึกถึง 24 เมษายน 2016 คงโมเดลไว้ตลอดการทดสอบ 25 เมษายน–22 พฤษภาคม แต่วันอนาคตใช้คำทำนายต่อเนื่องแทนยอดจริง ส่วนวิธีพื้นฐานใช้ค่าเฉลี่ย 28 วันที่รู้ล่าสุดคงที่ในแต่ละรอบสั่ง ไม่ใช้คำตอบอนาคตตัดสินใจ</p><p class="note">ยอดขาย M5 ใช้เป็นตัวแทนความต้องการ ซึ่งอาจไม่รวมความต้องการที่ร้านเดิมเคยขายไม่ได้ ผลนี้เป็นการจำลอง ไม่ยืนยันการลดของเสียจริง และไม่คิดต้นทุนหรือของที่หมดอายุหลังวันสุดท้าย ของเหลือและของกำลังส่งแสดงแยกไว้</p></section>`;
document.querySelector('.footnote').before(simView);
Object.keys(builtInModels).forEach(code=>{const option=document.createElement('option');option.value=code;option.textContent=code;byId('sim-item').append(option)});
let simulationResult=null;
function simRow(target,values){const row=document.createElement('tr');values.forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.append(cell)});target.append(row)}
byId('sim-run').addEventListener('click',()=>{byId('sim-error').textContent='';byId('sim-output').hidden=true;simulationResult=null;try{
 const options=Object.fromEntries(['lead','shelf','review','pack','initial'].map(k=>[k,Number(byId('sim-'+k).value)]));
 const code=byId('sim-item').value,model=builtInModels[code];
 const ai=simulateInventory(model,options,'ai',infer),baseline=simulateInventory(model,options,'baseline',infer);simulationResult={code,options,ai,baseline};
 byId('sim-description').textContent=`${code} · 25 เม.ย.–22 พ.ค. 2016 · รอรับ ${options.lead} วัน · อายุ ${options.shelf} วัน · สั่งทุก ${options.review} วัน · แพ็ก ${options.pack} · ของเริ่มต้น ${options.initial} · ยอดขายจริงรวม ${ai.demand} หน่วย`;
 byId('sim-summary').replaceChildren();for(const [label,r]of [['AI · Linear Regression',ai],['ค่าเฉลี่ยย้อนหลัง 28 วัน',baseline]])simRow(byId('sim-summary'),[label,r.shortage+' หน่วย',r.waste+' หน่วย',r.service===null?'ไม่มีความต้องการ':r.service.toFixed(1)+'%',r.remaining+' / '+r.inTransit]);
 byId('sim-verdict').textContent=`AI ของขาด ${ai.shortage<baseline.shortage?'น้อยกว่า':ai.shortage>baseline.shortage?'มากกว่า':'เท่ากับ'}วิธีพื้นฐาน และหมดอายุ ${ai.waste<baseline.waste?'น้อยกว่า':ai.waste>baseline.waste?'มากกว่า':'เท่ากับ'}วิธีพื้นฐาน ลองเปลี่ยนอายุหรือเวลารับของแล้วกดจำลองอีกครั้ง`;
 byId('sim-days').replaceChildren();ai.rows.forEach(r=>simRow(byId('sim-days'),[r.date,r.ordered,r.received,r.actual,r.sold,r.shortage,r.waste,r.closing]));byId('sim-output').hidden=false;
 }catch(e){byId('sim-error').textContent=e.message}});
['item','lead','shelf','review','pack','initial'].forEach(k=>byId('sim-'+k).addEventListener(k==='item'?'change':'input',()=>{byId('sim-output').hidden=true;simulationResult=null}));
byId('sim-export').addEventListener('click',()=>{if(!simulationResult)return;const {code,options,ai,baseline}=simulationResult;downloadCSV([['วิธี','สินค้า','รอรับวัน','อายุวัน','รอบสั่งวัน','แพ็ก','ของเริ่มต้น','วันที่','สั่ง','รับ','ยอดจริง','ขายได้','ขาด','หมดอายุ','เหลือ'],...[["AI",ai],["ค่าเฉลี่ย28วัน",baseline]].flatMap(([method,r])=>r.rows.map(d=>[method,code,options.lead,options.shelf,options.review,options.pack,options.initial,d.date,d.ordered,d.received,d.actual,d.sold,d.shortage,d.waste,d.closing]))],'inventory_simulation.csv')});
