async function api(path,body){try{const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'X-Forecast-App':'1','Content-Type':'text/plain;charset=utf-8'},body});const value=await r.json();if(!r.ok)throw new Error(value.error);return value}catch(e){if(e instanceof TypeError)throw new Error('เชื่อมต่อไม่ได้ ตรวจว่าหน้าต่างเซิร์ฟเวอร์ยังเปิดอยู่ แล้วลองใหม่');throw e}}
const savedCard=document.createElement('section');savedCard.className='card saved-card';
savedCard.innerHTML='<div class="card-head"><h2>ประวัติคำแนะนำซื้อ</h2><span class="small-label" id="saved-count"></span></div><p class="note">บันทึกคำแนะนำที่คำนวณแล้ว เพื่อกลับมาเปิดดูภายหลัง</p><button id="save-purchase" disabled>บันทึกคำแนะนำซื้อนี้</button><p id="save-status" role="status" aria-live="polite"></p><div id="saved-list"></div>';
document.querySelector('[data-view="purchase"]').append(savedCard);
const saveButton=byId('save-purchase'),savedStatus=byId('save-status'),savedList=byId('saved-list');
let busy=false,datasetId='m5',savedFingerprint='',pendingFingerprint='',requestId='';
const controls=['import','reset-data','forecast','export','export-test','item','date','csv-file','buy','export-buy','stock','pack'];
function fingerprint(){return latestPurchase?JSON.stringify(latestPurchase):''}
function syncSave(){saveButton.disabled=busy||!latestPurchase||fingerprint()===savedFingerprint;saveButton.textContent=latestPurchase&&fingerprint()===savedFingerprint?'บันทึกคำแนะนำนี้แล้ว':'บันทึกคำแนะนำซื้อนี้';byId('buy').disabled=busy||!latestResult}
function setBusy(value){busy=value;controls.forEach(id=>byId(id).disabled=value);byId('export').disabled=value||!latestResult;byId('export-buy').disabled=value||!latestPurchase;syncSave()}
function showSaved(rows){
 savedList.replaceChildren();byId('saved-count').textContent=rows.length+' รายการ';
 if(!rows.length){const p=document.createElement('p');p.className='saved-empty';p.textContent='ยังไม่มีประวัติ เริ่มจากทำนายยอดขายและคำนวณจำนวนซื้อ';savedList.append(p);return}
 const wrap=document.createElement('div');wrap.className='saved-table-wrap';const table=document.createElement('table');table.className='saved-table';table.innerHTML='<thead><tr><th>วันเป้าหมาย / สินค้า</th><th>จำนวนซื้อ</th><th>บันทึกเมื่อ</th></tr></thead>';const tbody=document.createElement('tbody');
 for(const r of rows.slice(0,20)){const tr=document.createElement('tr');const a=document.createElement('td'),b=document.createElement('td'),c=document.createElement('td');const code=document.createElement('strong');code.textContent=r.item;const detail=document.createElement('small');detail.textContent=r.date+' · '+(r.datasetName||'รายการเดิม');a.append(code,detail);const units=document.createElement('strong');units.textContent=r.units.toLocaleString('th-TH')+' หน่วย';const pack=document.createElement('small');pack.textContent=r.packs+' แพ็ก × '+r.pack+' · ของเหลือ '+r.stock;b.append(units,pack);c.textContent=new Date(r.savedAt).toLocaleString('th-TH');tr.append(a,b,c);tbody.append(tr)}table.append(tbody);wrap.append(table);savedList.append(wrap);
 if(rows.length>20){const p=document.createElement('p');p.className='note';p.textContent='แสดง 20 รายการล่าสุด';savedList.append(p)}
}
function useSaved(dataset){savedFingerprint='';pendingFingerprint='';requestId='';datasetId=dataset.id||dataset.savedAt;models=dataset.models;imported=true;populate();byId('import-status').textContent='ใช้ชุดข้อมูลที่บันทึกไว้ · '+Object.keys(models).length+' สินค้า';byId('method-note').textContent='ใช้ Ridge Regression แยกตามสินค้า กัน 28 วันสุดท้ายไว้ทดสอบแบบทำนายทีละวัน โดยไม่ใช้ชุดทดสอบฝึกโมเดลประเมิน ส่วนวันถัดไปใช้แบบจำลองที่ฝึกด้วยข้อมูลทั้งหมด ข้อมูลและโมเดลถูกบันทึกในเครื่องที่เปิดเซิร์ฟเวอร์';savedStatus.textContent='';syncSave()}
byId('import').addEventListener('click',async e=>{e.stopImmediatePropagation();if(busy)return;setBusy(true);byId('import-error').textContent='';try{const file=byId('csv-file').files[0];if(!file)throw new Error('เลือกไฟล์ CSV ก่อน');if(file.size>5*1024*1024)throw new Error('ไฟล์ต้องไม่เกิน 5 MB');byId('import-status').textContent='กำลังตรวจ ฝึกโมเดล และบันทึกข้อมูล…';useSaved(await api('/api/import',await file.text()))}catch(err){byId('import-error').textContent=err.message;byId('import-status').textContent='นำเข้าไม่สำเร็จ ยังคงใช้ชุดข้อมูลเดิม'}finally{setBusy(false)}},true);
byId('reset-data').addEventListener('click',async e=>{e.stopImmediatePropagation();if(busy)return;setBusy(true);try{await api('/api/reset','');datasetId='m5';savedFingerprint='';pendingFingerprint='';requestId='';models=builtInModels;imported=false;byId('method-note').textContent=m5Note;byId('date-help').textContent=m5Help;populate();byId('csv-file').value='';byId('import-error').textContent='';savedStatus.textContent='';byId('import-status').textContent='กลับมาใช้ข้อมูลตัวอย่าง M5 แล้ว ประวัติคำแนะนำซื้อยังเก็บไว้'}catch(err){byId('import-error').textContent=err.message}finally{setBusy(false)}},true);
saveButton.addEventListener('click',async()=>{if(busy||!latestPurchase)return;const current=fingerprint();if(current===savedFingerprint)return;if(current!==pendingFingerprint){pendingFingerprint=current;requestId=crypto.randomUUID()}const payload={...latestPurchase,datasetId,requestId};setBusy(true);savedStatus.textContent='กำลังบันทึก…';try{await api('/api/purchases',JSON.stringify(payload));savedFingerprint=current;savedStatus.textContent='บันทึกคำแนะนำซื้อแล้ว';try{showSaved((await api('/api/workspace')).purchases)}catch{savedStatus.textContent='บันทึกแล้ว แต่โหลดประวัติไม่ได้ กรุณารีโหลดเพื่อดูรายการ'}}catch(e){savedStatus.textContent=e.message}finally{setBusy(false)}});
['item','date','stock','pack','forecast','buy'].forEach(id=>byId(id).addEventListener(id==='forecast'||id==='buy'?'click':id==='item'?'change':'input',()=>{savedStatus.textContent='';syncSave()}));
setBusy(true);byId('import-status').textContent='กำลังเปิดข้อมูลที่บันทึกไว้…';
api('/api/workspace').then(state=>{if(state.dataset)useSaved(state.dataset);else byId('import-status').textContent='กำลังใช้ข้อมูลตัวอย่าง M5';showSaved(state.purchases)}).catch(e=>{byId('import-error').textContent='โหลดข้อมูลที่บันทึกไว้ไม่ได้: '+e.message;byId('import-status').textContent='ยังโหลดชุดข้อมูลไม่ได้ กรุณารีโหลดก่อนบันทึกคำแนะนำ';datasetId='unavailable'}).finally(()=>setBusy(false));
